name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build
        run: |
          make build

      - name: Run
        run: |
          ./cmd2s3 2>&1 | grep "usage: cmd2s3"
